### ISSUE TITLE
Link download not found ( missing download link )

### ISSUE THREAD

**Issue by rivawahyuda** [adi1090x/archlinux#1]
![Screenshot_2020-02-06_14-49-50](https://user-images.githubusercontent.com/13045558/73916456-0c10cd00-48f0-11ea-9474-5dfac02eeedb.png)

**Comment by niscita** [comment]
if your os running linux, you can build manually with instruction on README.md.

maybe @adi1090x  will add .iso soon

**Comment by adi1090x** [comment]
I'm currently working on documentations, So yeah, it'll take some time. if you're already using arch linux, you can build it, if not... please try after 2-3 days, i'll upload the ISO. I'm very busy these days, still i'm trying to manage. 
thanks for patience!
