### ISSUE TITLE
Additional configurations needed when using Luks-encrypted root

### ISSUE THREAD

**Issue by Zwo1in** [adi1090x/archlinux#2]
Hi,
I've just finished this wonderful installation with Luks-encrypted root. I'm unsure if I should open an issue for that but I had to make following changes in order to boot with success:

- uncomment this line in `/etc/default/grub`
  ```
  #GRUB_ENABLE_CRYPTODISK=y
  ```
- change `encrypt` hook to `plymouth-encrypt` in `/etc/mkinitcpio.conf`
- add DejaVuSans.ttf to `/usr/share/fonts/TTF`
- `cp -r /usr/share/grub/themes/Tela /boot/grub/themes/Tela` and adjust path in `/etc/default/grub`
- rerun `mkinitcpio -P` and `grub-mkconfig -o /boot/grub/grub.cfg`

**Comment by adi1090x** [comment]
Great, thanks for letting me know... thing is when i created this installation, i didn't consider LUKS or Encryption necessary, however... I'll try to do it the next project.
