### ISSUE TITLE
Stuck After Login The LXDM (liveuser)

### ISSUE THREAD

**Issue by anwareset** [adi1090x/archlinux#4]
Helo, I'm not sure what to give you about this. I don't understand how to get the log. Can you explain to me? Because it's stuck with grey background after login with LXDM. So I never had chances to install it on my machine.

EDIT:
It's only happen when login with Openbox/Default session. i3 and LXDE seems fine.

## Hardware Details
| Item      | Value                        |
| ----------|:----------------------------:|
| Vendor    | Lenovo                       |
| Model     | G485                         |
| Type      | Notebook/Laptop              |
| CPU       | AMD E-300 1.30GHz Dualcore   |
| RAM       | Kingston 4GB DDR3 12800 PC3L |
| GPU       | AMD ATI Radeon HD 6310       |
| Disk      | HDST HDD 320GB 5400rpm       |
| Display   | LCD HD 14" TFT 1366x768 60Hz |
| Used from | 2011                         |

**Comment by brneor** [comment]
Had the same issue and found out it was the compton config, maybe the shadows, I don't really know. Login using i3 or lxde and install it normally. If want to use openbox, make a backup of compton config file and start a new one.

**Comment by anwareset** [comment]
> Had the same issue and found out it was the compton config, maybe the shadows, I don't really know. Login using i3 or lxde and install it normally. If want to use openbox, make a backup of compton config file and start a new one.

Can you please give us your modified compton's config here?
