### ISSUE TITLE
Setup is very unreliable

### ISSUE THREAD

**Issue by zQueal** [adi1090x/archlinux#5]
![VirtualBoxVM_wxYvwnp9qB](https://user-images.githubusercontent.com/239193/78310678-aa9a6280-751c-11ea-93c5-0dff5ccbc39a.png)

Constant errors of;

> error: copy-fd: write returned: No space left on device

Despite more than 45GB left on device.

Additionally;

![VirtualBoxVM_ZcI8mmehJs](https://user-images.githubusercontent.com/239193/78310712-c3a31380-751c-11ea-87c6-2d84bd41d167.png)

**Comment by adi1090x** [comment]
Are you trying to `build the ISO` ***inside the live ISO?***

**Comment by zQueal** [comment]
Yes. I used the ISO for the arch environment in a VM.

**Comment by adi1090x** [comment]
to build the ISO, you need 10+gb space.
use `cow_spacesize=10G `,  in grub for free space in live ISO.

**Comment by zQueal** [comment]
Thanks! I must have been misunderstanding some things.
