### ISSUE TITLE
Installer patch to provide proper progress for the install process

### ISSUE THREAD

**Issue by salientos** [adi1090x/archlinux#6]
Hi Adi,

I adjusted the code to allow a dialog progress when the actual install occurs, so instead of the end user seeing all the text fly up the screen, they get a progress bar. I've linked to the line that needs changing. It does however, rely on [pv](http://www.ivarch.com/programs/pv.shtml) being installed too. Replace the rsync line with the following:

https://github.com/adi1090x/archlinux/blob/f9c929c18e87afdf8759cdaa507a55f39ba6ab75/customiso/airootfs/abif-master/abif#L1440

```bash
	 # set the counter for pv data
     counter=$(find /run/archiso/sfs/airootfs/ | wc -l)

	 # give rsync a progress bar as we install using pv and dialog
     rsync -av --no-i-r ${AIROOTIMG} ${MOUNTPOINT}/ 2>/tmp/.errlog | \
      pv -len --size ${counter} --interval 1.0 2>&1 >/dev/null | \
      dialog --backtitle "$VERSION - $SYSTEM ($ARCHI)" --title "$VERSION - $SYSTEM ($ARCHI)" --gauge "\n$INSTALLTEXT" 10 75
```
It also displays whether the boot mode is BIOS or UEFI within the title

Hope it's useful!

**Comment by adi1090x** [comment]
Great, thanks. I'll try it and update the code.
