### ISSUE TITLE
archlinux-2020.02.09-x86_64.iso liveuser issues

### ISSUE THREAD

**Issue by ryanlath** [adi1090x/archlinux#7]
I downloaded the iso.  Booted it up.  I had some problems...

1) default/openbox, after login would end up on a solid background, mouse cursor, nothing else.  Could not use keyboard, could not use mouse for anything.   If I moved to a different terminal, I could kill compton and it would become usable.  I think.

2) I3: I could log in, but couldn't use the keyboard or mouse for anything, but... F12/print screen would bring up whatever that pgm was.  That was all I could do.  Even if I moved to a different terminal and killed compton, nothing.

3) lxde: this seemed to work.

FWIW, I've attached an lshw output...

[lshw.txt](https://github.com/adi1090x/archlinux/files/4572987/lshw.txt)

**Comment by adi1090x** [comment]
it's maybe the compton blur issue, I've fixed it, will upload the new ISO soon.
